wrap React.PropsWithChildren
jemise111/react-native-swipe-list-view pull request #598
Opened 2022-04-27 05:52 UTC by KAMEDAkyosuke

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/55dc209ceb6dbcd59c4c68cc8dfb77faadd9de12
children is removed on React 18

Thanks for submitting a pull request!

**Please confirm you have linted your code and fixed any issues:**

* [ ] I ran `yarn run fix` on my PR and fixed any formatting issues

execute result. None were relevant to this fix.

```
% yarn run fix                           
yarn run v1.22.10
$ yarn run prettier && yarn run lint
$ prettier --write --loglevel=warn "**/*.js"
$ eslint . --ext .js

/path/to/react-native-swipe-list-view/SwipeListExample/example.js
  46:29  warning  Inline style: { backgroundColor: "mode === type ? 'grey' : 'white'" }  react-native/no-inline-styles

/path/to/react-native-swipe-list-view/SwipeListExample/examples/actions.js
   84:40  warning  Inline style: { backgroundColor: 'lightgreen' }  react-native/no-inline-styles
   91:44  warning  Inline style: { backgroundColor: 'lightgreen' }  react-native/no-inline-styles
  142:44  warning  Inline style: { backgroundColor: 'lightgreen' }  react-native/no-inline-styles
  159:29  warning  Inline style: { flex: 1 }                        react-native/no-inline-styles

/path/to/react-native-swipe-list-view/SwipeListExample/examples/per_row_config.js
  35:31  warning  Missing radix parameter  radix

/path/to/react-native-swipe-list-view/SwipeListExample/examples/sectionlist.js
  21:31  warning  '_' is already declared in the upper scope  no-shadow

/path/to/react-native-swipe-list-view/bin/dev.js
  42:44  warning  'err' is already declared in the upper scope  no-shadow

/path/to/react-native-swipe-list-view/components/SwipeRow.js
  634:28  warning  Inline style: { zIndex: 2 }  react-native/no-inline-styles
  648:28  warning  Inline style: { zIndex: 2 }  react-native/no-inline-styles

/path/to/react-native-swipe-list-view/types/flowtypes.js
  2:0  warning  Unexpected unlimited 'eslint-disable' comment. Specify some rule names to disable  eslint-comments/no-unlimited-disable
  2:1  warning  ESLint rules are disabled but never reported                                       eslint-comments/no-unused-disable

✖ 12 problems (0 errors, 12 warnings)

✨  Done in 4.68s.
```

**Please provide information on what your PR achieves and any issues that it addresses:**

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/55dc209ceb6dbcd59c4c68cc8dfb77faadd9de12
children is removed on React 18. So I add.

2023-01-13 13:53 UTC, DianaKoenraadt commented
Can this be merged please?

2023-01-19 02:31 UTC, vickycabrera commented
I need it too u.u

2023-01-19 06:39 UTC, KAMEDAkyosuke commented
@jemise111 Would you review/merge/release this for us?

2023-01-19 14:28 UTC, vickycabrera approved these changes

2023-01-19 15:52 UTC, lethib commented
I was also expecting this PR to be merged. 

You can fix it on your own using [`patch-package`](https://github.com/ds300/patch-package#readme) ! 
Steps are also really well described in [this video](https://youtu.be/2AVs-Yh1bS8).

2023-01-20 23:27 UTC, vickycabrera commented
> I was also expecting this PR to be merged.
> 
> You can fix it on your own using [`patch-package`](https://github.com/ds300/patch-package#readme) ! Steps are also really well described in [this video](https://youtu.be/2AVs-Yh1bS8).

Thank you, I will try it while await for merge

2023-03-21 21:05 UTC, brunomacedo approved these changes

2023-03-21 21:08 UTC, brunomacedo commented
I also need this fix

2023-03-31 20:37 UTC, robwalkerco requested changes
I'm not a maintainer or anything on this project, but I don't think this PR could be merged in its current state.

I've offered some suggestions to tidy up the import you added.

2023-03-31 20:37 UTC, robwalkerco commented on types/index.d.ts
>  import { Component } from 'react';
```suggestion
import { Component, PropsWithChildren } from 'react';
```

2023-03-31 20:37 UTC, robwalkerco commented on types/index.d.ts
> +export class SwipeRow<T> extends Component<Partial<React.PropsWithChildren<IPropsSwipeRow<T>>>> {
```suggestion
export class SwipeRow<T> extends Component<Partial<PropsWithChildren<IPropsSwipeRow<T>>>> {
```

2026-06-14 15:52 UTC, jemise111 commented
Children typing is handled in the v4 TypeScript rewrite (`4.0.0-rc.0`, `@next`). Closing as addressed — appreciate the PR.

2026-06-14 15:52 UTC, closed without merging